version: "3.7"
services:
  database:
    container_name: FaceitBackendDB
    image: postgres:14.5-bullseye
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
    volumes:
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init.sql
  faceit-backend-app:
    container_name: FaceitBackendApp
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"